name: "SAST scan"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code
    steps:
      - uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: alphayax/appscan-sast-action@v1
        with:
          api-secret: "${{secrets.ASOC_SECRET}}"
          api-id: "${{secrets.ASOC_KEY}}"
          application-id: "05440f8f-1eb0-49e7-a13b-c25214e3f031"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

ASOC_DAST scan
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and DAST scan on the target url
    steps:
      - uses: actions/checkout@v2
      - name: Run AppScan CodeSweep
        uses: alphayax/appscan-dast-action@v1
      with:
        target: http://demo.testfire.net/
          user-id: "admin"
          password: "admin"
        api-secret: "${{secrets.ASOC_SECRET}}"
        api-id: "${{secrets.ASOC_KEY}}"
        application-id: "b05d53a3-3c6d-4b93-a764-510916539af2"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}