name: "SAST scan"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code
    steps:
      #- uses: actions/checkout@v1
      #- name: Run AppScan CodeSweep
      #  uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
      #  with:
      #    asoc_key: ${{secrets.ASOC_KEY}}
      #    asoc_secret: ${{secrets.ASOC_SECRET}}
    #env:
      #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
  #needs: build
  #name: Run the SAST scan on the source code
  #steps:
      - uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: alphayax/appscan-sast-action@v1
        with:
          #target: http://demo.testfire.net/
          api-secret: "${{secrets.ASOC_SECRET}}"
          api-id: "${{secrets.ASOC_KEY}}"
          application-id: "cccb700c-1188-44e6-9d05-b5a287d1eca2"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  zap_scan:
    runs-on: ubuntu-latest
    #needs: security
    name: Run DAST scan on the web application
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: master
        - name: ZAP Scan
          uses: zaproxy/action-baseline@v0.6.1
          with:
            docker_name: 'owasp/zap2docker-stable'
            target: 'http://demo.testfire.net/'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'