name: "SonarCloud analysis"
on: push
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Analyze with SonarCloud         

      
        uses: SonarSource/sonarcloud-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
          with:
            -Dsonar.projectKey=dubeyshagun29 \
            -Dsonar.organization=Dubeyshagun29_HCL_Demo \
            -Dsonar.host.url=https://sonarcloud.io
 
