name: Main Workflow
on: push
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        #Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        #projectBaseDir: /opt/sonar-scanner/output
        args: >
          -Dsonar.organization=dubeyshagun29
          -Dsonar.projectKey=Dubeyshagun29_HCL_Demo
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.exclusions=**/obj/**,**/*.dll
          -Dsonar.java.binaries=.