name: SonarCloud analysis
on: push
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    name: SonarCloud
    steps:
      - name: Analyze with SonarCloud
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- name: SonarCloud Scan
        #uses: sonarsource/sonarcloud-github-action@master

        #with:
          #projectBaseDir: "C:/Users/ShagunDubey/New folder/HCL_Demo"
          - name: Analyze with SonarCloud
            uses: sonarsource/sonarcloud-github-action@master
            with:
              projectBaseDir: C:/Users/ShagunDubey/New folder/HCL_Demo
              args: >
                -Dsonar.projectKey=Dubeyshagun29_HCL_Demo
                -Dsonar.organization=dubeyshagun29
                -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
       
         #with:
          # projectBaseDir: github/workspace/Dubeyshagun29/HCL_Demo/AltoroJ-AltoroJ-3.2
            #C:/Users/Shagun Dubey/OneDrive/Desktop/AltoroJ-AltoroJ-3.2/HCL_Demo/HCL_Demo/AltoroJ-AltoroJ-3.2 


 

