name: "StackHawk"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '33 14 * * 1'

permissions:
  contents: read

jobs:
  stackhawk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for stackhawk/hawkscan-action to upload code scanning alert info
    name: StackHawk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        continue-on-error: true                   # ✏️ Set to false to break your build on scan errors
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
          
outputFile: hawkscan-report.json  # ✅ Ensures the report is saved
continue-on-error: false  # ✅ Prevents next steps if scan fails
  
      - name: Convert StackHawk Report to GitHub Issues
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: hawkscan-report.json  # ✅ Ensure this file is generated from the StackHawk scan
          update_existing: true  # ✅ Avoids duplicate issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Fix: Use GitHub Token as an environment variable

